spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board
    username: choahra
    password: dkfk0518

  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
